openapi: "3.0.3"

info:
  title: "Show Review API"
  version: "1.0.0"

paths:
  "/shops/{shopId}/reviews":
    get:
      summary: "Get Specified shop reviews"  
      description: "(description): Get Specified shop reviews"
      tags: ["shops"]
      deprecated: false
      parameters:
        - name: shopId
          in: path
          required: true
          schema: { type: string }
      responses:
        "200":
          description: "Success Operation"
